/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        "primary-light": "var(--primary-light)",
        secondary: "var(--secondary)",
        accent: "var(--accent)",
        card: "var(--card)",
        border: "var(--border)",
        muted: "var(--muted)",
        purple: {
          500: "var(--purple-500)",
          600: "#7c3aed",
        },
        blue: {
          500: "var(--blue-500)",
        },
        yellow: {
          500: "var(--yellow-500)",
        },
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  safelist: [
    "from-purple-500",
    "to-blue-500",
    "text-yellow-500",
    "fill-yellow-500",
    "bg-yellow-500",
    "bg-purple-500",
    "bg-blue-500",
    "from-purple-600",
    "to-blue-600",
    "bg-primary",
    "bg-primary-light",
    "bg-secondary",
    "bg-accent",
    "bg-card",
    "bg-background",
    "text-primary",
    "text-foreground",
    "text-muted",
    "border-border",
    "border-primary",
    "flex",
    "flex-col",
    "items-center",
    "justify-center",
    "justify-between",
    "gap-2",
    "gap-4",
    "gap-8",
    "grid",
    "grid-cols-1",
    "md:grid-cols-2",
    "lg:grid-cols-2",
    "lg:grid-cols-3",
    "p-4",
    "p-6",
    "px-4",
    "py-2",
    "py-4",
    "py-6",
    "m-2",
    "m-4",
    "mx-auto",
    "my-4",
    "my-8",
    "mt-4",
    "mt-8",
    "mb-4",
    "mb-8",
    "text-center",
    "text-left",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-3xl",
    "text-4xl",
    "md:text-5xl",
    "lg:text-6xl",
    "font-bold",
    "font-medium",
    "rounded-md",
    "rounded-lg",
    "rounded-full",
    "w-full",
    "w-10",
    "h-10",
    "max-w-7xl",
    "max-w-2xl",
    "sm:flex-row",
    "md:flex",
    "md:block",
    "md:hidden",
    "lg:mx-0",
    "lg:justify-start",
    "hidden",
    "transition",
    "duration-300",
    "hover:bg-primary-light",
    "hover:shadow-lg",
  ],
  plugins: [],
};
